apiVersion: apps/v1
kind: Deployment
metadata:
  name: lc-db-deployment
  labels:
    app: lc-db
  namespace: lc-saas-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lc-db
  template:
    metadata:
      labels:
        app: lc-db
    spec:
      containers:
        - name: lc-db
          image: postgres:15.3-alpine
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: lc-db-pv
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: lc-db-secret
                  key: postgres-db
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: lc-db-secret
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lc-db-secret
                  key: postgres-password
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
      volumes:
        - name: lc-db-pv
          persistentVolumeClaim:
            claimName: lc-db-pvc
