apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lc-db-pvc
  namespace: lc-saas-ns
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: lc-db-sc
